### ISSUE TITLE
Error: The package "@cloudflare/workerd-darwin-64" could not be found

### ISSUE THREAD

**Issue by datascienceqing** [Sh4yy/personal-ai#5]
Darwin 23.4.0
node v16.17.1
npm  v9.6.4

I got this error when ran "npx wrangler login"

"""
/Users/XXX/personal-ai/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

Error: The package "@cloudflare/workerd-darwin-64" could not be found, and is needed by workerd.
"""
I ran "npm install -g @cloudflare/wrangler" to install the package. The installation was successful, but the error persists. GitHub Copilot said there is no @cloudflare/workerd-darwin-64 package publicly on npm. 

I am not sure how to resolve the issue?

**Comment by MendyLanda** [comment]
That's weird but regardless there *is* such a package on npm:

https://www.npmjs.com/package/@cloudflare/workerd-darwin-64

If you run just `npx wrangler` it works?

**Comment by datascienceqing** [comment]
"npm i @cloudflare/workerd-darwin-64 " works. 
Thanks
